### ISSUE TITLE
Fix missing requirements from adding collapsibility platform

### ISSUE THREAD

**Issue by dtch1997** [mcx-lab/rl-baselines3-zoo#7]
Recent commits in master may have added additional requirements which are not reflected in `requirements.txt`

Full stack trace: 

```
Executing command: python train.py --algo ppo --env A1GymEnv-v0 --save-freq 100000 | tee run.log
pybullet build time: Aug 16 2021 13:56:42
Traceback (most recent call last):
  File "train.py", line 185, in <module>
========== A1GymEnv-v0 ==========
Seed: 1754643910
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 128),
             ('clip_range', 0.4),
             ('ent_coef', 0.0),
             ('env_wrapper', 'sb3_contrib.common.wrappers.TimeFeatureWrapper'),
             ('gae_lambda', 0.9),
             ('gamma', 0.99),
             ('learning_rate', 3e-05),
             ('max_grad_norm', 0.5),
             ('n_envs', 16),
             ('n_epochs', 20),
             ('n_steps', 512),
             ('n_timesteps', 2000000.0),
             ('normalize', True),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs',
              'dict(log_std_init=-2, ortho_init=False, activation_fn=nn.ReLU, '
              'net_arch=[dict(pi=[256, 256], vf=[256, 256])] )'),
             ('sde_sample_freq', 4),
             ('use_sde', True),
             ('vf_coef', 0.5)])
Using 16 environments
Creating test environment
    model = exp_manager.setup_experiment()
  File "/home/dtch1997/code/rl-baselines3-zoo/utils/exp_manager.py", line 157, in setup_experiment
    self.create_callbacks()
  File "/home/dtch1997/code/rl-baselines3-zoo/utils/exp_manager.py", line 413, in create_callbacks
    self.create_envs(self.n_eval_envs, eval_env=True),
  File "/home/dtch1997/code/rl-baselines3-zoo/utils/exp_manager.py", line 497, in create_envs
    env = make_vec_env(
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/stable_baselines3/common/env_util.py", line 80, in _init
    env = gym.make(env_id, **env_kwargs)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/gym/envs/registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/gym/envs/registration.py", line 75, in make
    cls = load(self.entry_point)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/home/dtch1997/anaconda3/envs/rl-baselines3-zoo/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dtch1997/code/rl-baselines3-zoo/blind_walking/envs/gym_envs/__init__.py", line 2, in <module>
    from blind_walking.envs.gym_envs.a1_gym_env import A1GymEnv
  File "/home/dtch1997/code/rl-baselines3-zoo/blind_walking/envs/gym_envs/a1_gym_env.py", line 4, in <module>
    from blind_walking.envs import env_builder
  File "/home/dtch1997/code/rl-baselines3-zoo/blind_walking/envs/env_builder.py", line 16, in <module>
    from blind_walking.envs import locomotion_gym_env
  File "/home/dtch1997/code/rl-baselines3-zoo/blind_walking/envs/locomotion_gym_env.py", line 30, in <module>
    from blind_walking.envs.env_wrappers.collapsibleplatform import CollapsiblePlatform
  File "/home/dtch1997/code/rl-baselines3-zoo/blind_walking/envs/env_wrappers/collapsibleplatform.py", line 6, in <module>
    import pyquaternion
ModuleNotFoundError: No module named 'pyquaternion'
```

**Comment by dtch1997** [comment]
@jennyzzt if you managed to get this to work, could you update the requirements
